
development:
  adapter: mysql2
  database: tdf_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: tdf_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: tdf_pro
  username: root
  password:
  socket: /tmp/mysql.sock
